def func():
	raise Exception('test')

def main():
	try:
		func()
	except Exception:
		print('CAUGHT')
