def main():
	try:
		raise Exception('error')
	except Exception:
		print('CAUGHT')
